import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import axios from 'axios'

export default function Home( ) {
  
  const [data, setData ] = useState()
  
  async function getStatus(){
    const response = await axios.get('https://doar-computador-api.herokuapp.com/')
    setData(response.data)
    console.log(response.data.alive)
  }

  useEffect(()=>{
    getStatus()
  }, [])
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Doar Computadores</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <h1 className={styles.title}>
          Doação de computadores usados
        </h1>
        
        {data && <> 
          <h2 className={styles.apiStatus}>
          <p style={{color: data.alive ? 'green' : 'red'}}>Status : {data.alive ? 'API online' : 'API offline'}</p>
          </h2>
        </>
        }
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/crohnaro"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by CrohnaroDev
          
        </a>
      </footer>
    </div>
  )
}
